presets:
  camp_basic:
    include:
      - "tourism=camp_site"
    exclude:
      - "tents=no"
      - "camp_site:tent=no"

  camp_and_caravan:
    include:
      - "tourism=camp_site"
      - "tourism=caravan_site"
    exclude:
      - "tents=no"

  wild_camping_spots:
    include:
      - "camp_site=wild"

  shelters:
    include:
      - "amenity=shelter"

  hotel:
    include:
      - "tourism=hotel"

  accommodation:
    include:
      - "tourism=hotel"
      - "tourism=guest_house"
      - "tourism=bed_and_breakfast"

  drinking_water:
    include:
      - "amenity=drinking_water"
